# https://mroi.github.io/apple-internals/

com.apple.nearbyd
com.apple.dprivacyd
com.apple.locationd
com.apple.wifianalyticsd
com.apple.icloud.searchpartyd
com.apple.icloud.findmydeviced
com.apple.osanalytics.osanalyticshelper
com.apple.SubmitDiagInfo
com.apple.symptomsd-diag
com.apple.symptomsd
com.apple.rtcreportingd
com.apple.systemstats.daily
com.apple.systemstats.analysis
com.apple.systemstats.microstackshot_periodic
com.apple.backupd
com.apple.backupd-helper
com.apple.cloudd
com.apple.seld
com.apple.findmymacmessenger
com.apple.GameController.gamecontrollerd
com.apple.rapportd
com.apple.triald.system
com.apple.ecosystemanalyticsd
com.apple.liquiddetectiond
com.apple.countryd
com.apple.cameracaptured
com.apple.eligibilityd
com.apple.airportd
com.apple.AirPlayXPCHelper
com.apple.gamepolicyd
com.apple.corebrightnessd
com.apple.mobileassetd
com.apple.findmy.findmybeaconingd
com.apple.nfcd
com.apple.metadata.mds
com.apple.endpointsecurity.endpointsecurityd
org.cups.cupsd
com.apple.logd
com.apple.ReportCrash.Root
com.apple.audioanalyticsd
com.apple.logd_helper
com.apple.CrashReporterSupportHelper
com.apple.audio.audiomxd
com.apple.accessoryupdaterd
com.apple.ctkd
com.apple.modelcatalogd
com.apple.colorsync.displayservices
com.apple.modelmanagerd
com.apple.colorsyncd
com.apple.biomed

# coreaudiod
com.apple.audio.coreaudiod
com.apple.audio.systemsoundserverd
com.apple.timesync.audioclocksyncd
com.apple.audio.AudioComponentRegistrar

com.apple.coreduetd
com.apple.ospredictiond

com.apple.warmd
com.apple.DumpPanic
com.apple.analyticsd
com.apple.appleh13camerad
com.apple.bluetoothd
com.apple.contextstored
com.apple.mediaremoted
com.apple.mdmclient.daemon
com.apple.online-auth-agent.xpc

sudo launchctl bootout system/{name}
sudo launchctl disable system/{name}

com.apple.mdmclient.agent
com.apple.routined
com.apple.AppSSOAgent
com.apple.icdd
com.apple.controlcenter
com.apple.videoconference.camera
com.apple.studentd
com.apple.TextInputSwitcher
com.apple.feedbackd
com.apple.Spotlight
com.apple.AirPlayUIAgent
com.apple.accessibility.heard
com.apple.usernotificationsd
com.apple.lockdownmoded
com.apple.notificationcenterui.agent
com.apple.MobileAccessoryUpdater.fudHelperAgent
com.apple.BTServer.cloudpairing
com.apple.SecureBackupDaemon
com.apple.remindd
com.apple.diagnostics_agent
com.apple.voicebankingd
com.apple.commerce
com.apple.localizationswitcherd
com.apple.MENotificationService
com.apple.rapportd
com.apple.bird
com.apple.CommCenter
com.apple.corespeechd
com.apple.triald
com.apple.homed
com.apple.homeenergyd
com.apple.siriactionsd
com.apple.siriinferenced
com.apple.siriknowledged
com.apple.sirittsd
com.apple.SiriTTSTrainingAgent
com.apple.amp.mediasharingd
com.apple.sharingd
com.apple.businessservicesd
com.apple.avatarsd
com.apple.textunderstandingd
com.apple.peopled
com.apple.UserPictureSyncAgent
com.apple.translationd
com.apple.Safari.PasswordBreachAgent
com.apple.SafariHistoryServiceAgent
com.apple.email.maild
com.apple.icloudmailagent
com.apple.cmio.ContinuityCaptureAgent
com.apple.weatherd
com.apple.videosubscriptionsd
com.apple.UsageTrackingAgent
com.apple.universalaccessd
com.apple.telephonyutilities.callservicesd
com.apple.tipsd
com.apple.suggestd
com.apple.sidecar-relay
com.apple.ScreenTimeAgent
com.apple.quicklook
com.apple.quicklook.ui.helper
com.apple.quicklook.ThumbnailsAgent
com.apple.protectedcloudstorage.protectedcloudkeysyncing
com.apple.photolibraryd
com.apple.photoanalysisd
com.apple.newsd
com.apple.mediaanalysisd
com.apple.Maps.mapspushd
com.apple.ManagedClientAgent.enrollagent
com.apple.knowledge-agent
com.apple.itunescloudd
com.apple.intelligenceplatformd
com.apple.imautomatichistorydeletionagent
com.apple.imagent
com.apple.icloud.searchpartyuseragent
com.apple.iCloudNotificationAgent
com.apple.icloud.fmfd
com.apple.geodMachServiceBridge
com.apple.gamed
com.apple.followupd
com.apple.financed
com.apple.familynotificationd
com.apple.familycontrols.useragent
com.apple.familycircled
com.apple.donotdisturbd
com.apple.CoreLocationAgent
com.apple.cloudphotod
com.apple.cloudd
com.apple.dataaccess.dataaccessd
com.apple.calaccessd
com.apple.CallHistoryPluginHelper
com.apple.assistantd
com.apple.assistant_service
com.apple.ap.promotedcontentd
com.apple.ap.adprivacyd
com.apple.AMPArtworkAgent
com.apple.AMPDeviceDiscoveryAgent
com.apple.AMPLibraryAgent
com.apple.EscrowSecurityAlert
com.apple.transparencyd
com.apple.amsengagementd
com.apple.amsaccountsd
com.apple.Safari.SafeBrowsing.Service
com.apple.SafariBookmarksSyncAgent
com.apple.ReportCrash
com.apple.accessibility.MotionTrackingAgent
com.apple.corespotlightd
com.apple.corespotlightservice
com.apple.managedcorespotlightd
com.apple.spotlightknowledged.importer
com.apple.spotlightknowledged
com.apple.spotlightknowledged.updater
com.apple.contactsd
com.apple.geod
com.apple.geoanalyticsd
com.apple.appstoreagent
com.apple.swtransparencyd
com.apple.assistant_cdmd
com.apple.metrickitd
com.apple.audio.AudioComponentRegistrar
com.apple.SoftwareUpdateNotificationManager
com.apple.accessibility.axassetsd
com.apple.replicatord
com.apple.diagnosticextensionsd
com.apple.swcd
com.apple.mobiletimerd
com.apple.duetexpertd
com.apple.TextInputMenuAgent
com.apple.BiomeAgent
com.apple.colorsync.useragent
com.apple.webprivacyd
com.apple.AccessibilityVisualsAgent
com.apple.proactiveeventtrackerd
com.apple.biomesyncd
com.apple.SafariLaunchAgent
com.apple.dprivacyd
com.apple.Safari.History
com.apple.storedownloadd
com.apple.AddressBook.SourceSync
com.apple.AddressBook.abd
com.apple.exchange.exchangesyncd
com.apple.accessibility.AXVisualSupportAgent
com.apple.parentalcontrols.check
com.apple.CallHistorySyncHelper
com.apple.chronod
com.apple.generativeexperiences
com.apple.cache_delete
com.apple.identityservicesd

com.apple.Finder
com.apple.mlhostd
com.apple.wallpaper.agent
com.apple.knowledgeconstructiond
com.apple.ContextStoreAgent
com.apple.intelligencecontextd
com.apple.proactived

# screen sharing
com.apple.replayd

launchctl bootout gui/501/{name}
launchctl disable gui/501/{name}

com.apple.siri.context.service
com.apple.TextInputUI.xpc.CursorUIViewService
com.apple.geod
com.apple.accessibility.mediaaccessibilityd
com.apple.TextInputUI.xpc.CursorUIViewService
com.apple.siri.context.service

launchctl bootout user/501/{name}
launchctl disable user/501/{name}